- name: install nginx and ensure it is running
  hosts: web
  become: yes
  tasks:
  - name: install nginx
    ansible.builtin.package:
      name: nginx
      state: present
  - name: run and enable the nginx
    ansible.builtin.service:
      name: nginx
      state: started
      enabled: yes