- name: play1
  hosts: web
  tasks:
    - name: print message
      ansible.builtin.debug:
        msg: "hello from play1 and task1"
    - name: print message
      ansible.builtin.debug:
        msg: hello from play1 and task2

- name: play2
  hosts: web
  tasks:
    - name: print message
      ansible.builtin.debug:
        msg: "hell from play2"