- name: nginx playbook
  hosts: localhost
  become: yes
  tasks:
    - name: install nginx
      ansible.builtin.package:
        name: nginx
        state: present
    - name: run and enable the service
      ansible.builtin.service:
        name: nginx
        state: started
        enabled: yes